Adds `Giphy.trending` removed `Giphy.recent`
The `Giphy.trending` has been added to `Giphy::Client` deprecating
`Giphy::Client#recent` but it wasn't reflected at `Giphy` module level which was
causing `NoMethodError: undefined method `trending' for Giphy:Module` when
`Giphy.trending` was called.

Fixes: https://github.com/sebasoga/giphy/issues/8